name: Build

on: release

jobs:
  build:
    name: Build Bot
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Pull Project
        uses: actions/checkout@v3.5.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Preparing Project
        run: npm i

      - name: Building ContraBot
        run: tsc