name: Publish

#todo: change when done testing
on: release

jobs:
  build:
    name: Publish Bot
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Pull Project
        uses: actions/checkout@v3.5.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
              context: .
              push: true
              tags: "ghcr.io/contraversum/contrabot:latest"

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.KEY }}
                port: ${{ secrets.PORT }}
                script: cd memoriter/ && docker compose up -d --pull always contrabot
